### ISSUE TITLE
Call to SetSize on wrong TDescriptor

### ISSUE THREAD

**Issue by chris3k** [vanklompf/BlogSrc#2]
https://github.com/vanklompf/BlogSrc/blob/dcf54180b78ffdc25241f99cd16e588b0ebb7380/PacketDescriptorsProcessing/ProcessingBenchmark.h#L52-L54

Typo?
`s/pattern_likely.SetSize(50);/pattern_unlikely.SetSize(50);/`

**Comment by vanklompf** [comment]
Good catch. Fixed. I will later check if this has impact on results.
Fixed in: 016fad4af68859850933036788ce556dafadb2b9
